In [21]:
hdfs_path='/Adarsh/iris.csv'
cc.datasource_name='Cloudera CDH5 with Spark'
df_Iris_csv= cc.read_input_file(hdfs_path, use_input_substitution=False, execution_label="1")

In [22]:
print(df_Iris_csv)

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0    

In [23]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()


iris_df = df_Iris_csv.values
X = iris_df[:,:4] # features
y = le.fit_transform(iris_df[:,4]) # target
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [24]:
from sklearn.model_selection import train_test_split     # Every time we run train_test sample data is changing so unreliable
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.3)

In [25]:
from sklearn import svm
model=svm.SVC(kernel='rbf',C=30,gamma='auto')        # randomly initialized parameters
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

In [26]:
from sklearn.model_selection import cross_val_score

In [27]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),X,y,cv=5) # will give result of 5 folds

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [28]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),X,y,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [29]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),X,y,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

## Using For Loop to find optimal values of parameters

In [30]:
import numpy as np
kernels=['rbf','linear']
C=[1,5,10,20,30]
avg_scores={}
for kval in kernels:
    for cval in C:
        cv_scores=cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),X,y,cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)
        
avg_scores        

{'rbf_1': 0.9800000000000001,
 'rbf_5': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'rbf_30': 0.96,
 'linear_1': 0.9800000000000001,
 'linear_5': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'linear_30': 0.96}

## instead of using above approach we will use Grid Search CV

In [31]:
from sklearn.model_selection import GridSearchCV

clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
}, cv=5,return_train_score=False)

clf.fit(X,y)
clf.cv_results_

{'mean_fit_time': array([0.00063877, 0.00049191, 0.00057983, 0.00048089, 0.00060115,
        0.00045519]),
 'std_fit_time': array([7.46276812e-06, 8.30784446e-05, 3.70527326e-05, 8.50259621e-05,
        4.82012794e-05, 2.69091676e-05]),
 'mean_score_time': array([0.00028696, 0.00025635, 0.00026107, 0.00024314, 0.00026846,
        0.00025287]),
 'std_score_time': array([1.67237335e-05, 2.07878033e-05, 1.50796689e-05, 5.20473820e-06,
        1.62915098e-05, 1.36666887e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

In [32]:
# get result in Pandas Dataframe
import pandas as pd
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  mean_score_time  mean_test_score param_C param_kernel  \
0       0.000639         0.000287         0.980000       1          rbf   
1       0.000492         0.000256         0.980000       1       linear   
2       0.000580         0.000261         0.980000      10          rbf   
3       0.000481         0.000243         0.973333      10       linear   
4       0.000601         0.000268         0.966667      20          rbf   
5       0.000455         0.000253         0.966667      20       linear   

                          params  rank_test_score  split0_test_score  \
0      {'C': 1, 'kernel': 'rbf'}                1           0.966667   
1   {'C': 1, 'kernel': 'linear'}                1           0.966667   
2     {'C': 10, 'kernel': 'rbf'}                1           0.966667   
3  {'C': 10, 'kernel': 'linear'}                4           1.000000   
4     {'C': 20, 'kernel': 'rbf'}                5           0.966667   
5  {'C': 20, 'kernel': 'linear'}                5           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   std_fit_time  std_score_time  std_test_score  
0      0.000007        0.000017        0.016330  
1      0.000083        0.000021        0.016330  
2      0.000037        0.000015        0.016330  
3      0.000085        0.000005        0.038873  
4      0.000048        0.000016        0.036515  
5      0.000027        0.000014        0.042164

In [33]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

### Based on above result we can supply first 3 values to get best results

In [34]:
dir(clf) # object properties

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_check_is_fitted',
 '_estimator_type',
 '_get_param_iterator',
 '_get_param_names',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'fit_params',
 'get_params',
 'grid_scores_',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'refit',
 'return_train_scor

In [35]:
clf.best_score_

0.98

# Best Parameter 

In [36]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

### Randomized search CV to find optimal parameters with reduced computation load

In [37]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(svm.SVC(gamma='auto'),
                     {
                         'C':[1,5,10,20,50],
                         'kernel':['rbf','linear']
                     },
                     cv=5,
                     return_train_score=False,
                     n_iter=4
)   # n_iter to select random sample and reduce execution time
rs.fit(X,y)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      10          rbf         0.980000
1       1          rbf         0.980000
2      20       linear         0.966667
3      50       linear         0.966667

# Choosing best model

In [38]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

/opt/conda/envs/python3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/envs/python3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [39]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='ovr'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [41]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'],mp['params'], cv=5, return_train_score=False)
    clf.fit(X, y)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df
   

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000       {'n_estimators': 10}
2  logistic_regression    0.966667                   {'C': 5}